export default function () {
  /**
   * Init function loads tables, registers settings, and loads templates
   */
  Hooks.once("init", () => {

    loadTemplates([
      "systems/edrpg/templates/sheets/character-sheet.html",
      "systems/edrpg/templates/sheets/creature-sheet.html",
      "systems/edrpg/templates/sheets/npc-sheet.html",
      "systems/edrpg/templates/sheets/ship-sheet.html",
      "systems/edrpg/templates/sheets/vehicle-sheet.html",
      "systems/edrpg/templates/sheets/partials/actor-backgrounds.html",
      "systems/edrpg/templates/sheets/partials/actor-enhancements.html",
      "systems/edrpg/templates/sheets/partials/actor-combat.html",
      "systems/edrpg/templates/sheets/partials/actor-details.html",
      "systems/edrpg/templates/sheets/partials/actor-karma.html",
      "systems/edrpg/templates/sheets/partials/actor-main.html",
      "systems/edrpg/templates/sheets/partials/actor-skills.html",
      "systems/edrpg/templates/sheets/partials/equipment/armour.html",
      "systems/edrpg/templates/sheets/partials/equipment/clips-grenades.html",
      "systems/edrpg/templates/sheets/partials/equipment/close-combat.html",
      "systems/edrpg/templates/sheets/partials/equipment/cybernetics.html",
      "systems/edrpg/templates/sheets/partials/equipment/general.html",
      "systems/edrpg/templates/sheets/partials/equipment/ranged-weapons.html",
      "systems/edrpg/templates/sheets/partials/equipment/wearables.html",
      "systems/edrpg/templates/sheets/partials-ship/ship-main.html",
      "systems/edrpg/templates/sheets/partials-ship/ship-components.html",
      "systems/edrpg/templates/sheets/partials-ship/ship-crew.html",
      "systems/edrpg/templates/sheets/partials-ship/ship-equipment.html",
      "systems/edrpg/templates/items/ammo-clips.html",
      "systems/edrpg/templates/items/armour.html",
      "systems/edrpg/templates/items/backgrounds.html",
      "systems/edrpg/templates/items/commodities.html",
      "systems/edrpg/templates/items/cybernetics.html",
      "systems/edrpg/templates/items/enhancements.html",
      "systems/edrpg/templates/items/general-equipment.html",
      "systems/edrpg/templates/items/karma-capabilities.html",
      "systems/edrpg/templates/items/melee-weapons.html",
      "systems/edrpg/templates/items/wearables.html",
      "systems/edrpg/templates/items/ship-bulkheads.html",
      "systems/edrpg/templates/items/ship-fsd.html",
      "systems/edrpg/templates/items/ship-internal-afm-units.html",
      "systems/edrpg/templates/items/ship-internal-cargo-racks.html",
      "systems/edrpg/templates/items/ship-internal-collector-limpet.html",
      "systems/edrpg/templates/items/ship-internal-docking-computer.html",
      "systems/edrpg/templates/items/ship-internal-fsd-interdictor.html",
      "systems/edrpg/templates/items/ship-internal-fuel-scoop.html",
      "systems/edrpg/templates/items/ship-internal-hb-limpet-controller.html",
      "systems/edrpg/templates/items/ship-internal-hull-reinforcement-package.html",
      "systems/edrpg/templates/items/ship-internal-module-reinforcement-package.html",
      "systems/edrpg/templates/items/ship-internal-planetary-vehicle-hangars.html",
      "systems/edrpg/templates/items/ship-internal-prospector-limpet-controller.html",
      "systems/edrpg/templates/items/ship-internal-refineries.html",
      "systems/edrpg/templates/items/ship-internal-shield-cell-banks.html",
      "systems/edrpg/templates/items/ship-internal-shield-generators.html",
      "systems/edrpg/templates/items/ship-life-support.html",
      "systems/edrpg/templates/items/ship-power-distributors.html",
      "systems/edrpg/templates/items/ship-power-plant.html",
      "systems/edrpg/templates/items/ship-sensors.html",
      "systems/edrpg/templates/items/ship-shields.html",
      "systems/edrpg/templates/items/ship-thrusters.html",
      "systems/edrpg/templates/items/ship-utility-mounts.html",
      "systems/edrpg/templates/items/ship-weapons.html",
      "systems/edrpg/templates/items/vehicle-shields.html",
      "systems/edrpg/templates/items/vehicle-specials.html",
      "systems/edrpg/templates/items/vehicle-weapons.html",
      "systems/edrpg/templates/items/partials/item-all-header.html",
      "systems/edrpg/templates/items/partials/item-all-description.html",
      "systems/edrpg/templates/items/partials/item-all-cost.html",
      "systems/edrpg/templates/items/partials/item-all-count.html",
      "systems/edrpg/templates/items/partials/item-all-karma-cost.html",
      "systems/edrpg/templates/items/partials/item-all-notes.html",
      "systems/edrpg/templates/items/partials/item-all-armour.html",
      "systems/edrpg/templates/items/partials/item-all-effects.html",
      "systems/edrpg/templates/items/partials/item-all-melee-damage-bonus.html",
      "systems/edrpg/templates/items/partials/item-all-socialfactor.html",
      "systems/edrpg/templates/items/partials/item-all-enduranceAddition.html",
      "systems/edrpg/templates/items/partials/item-all-initiativeAddition.html",
      "systems/edrpg/templates/items/partials/item-all-resistKnockdown.html",
      "systems/edrpg/templates/items/partials/item-all-wearable.html",
      "systems/edrpg/templates/items/partials/item-ranged-weapon.html",
      "systems/edrpg/templates/items/partials/item-commodity.html",
      "systems/edrpg/templates/items/partials/item-backgrounds.html",
      "systems/edrpg/templates/items/partials/item-karma.html",
      "systems/edrpg/templates/items/partials/item-melee.html",
      "systems/edrpg/templates/items/partials/item-cybernetics.html",
      "systems/edrpg/templates/items/partials/item-skill-attributes.html",
      "systems/edrpg/templates/items/partials/item-ship-all-items.html",
      "systems/edrpg/templates/items/partials/item-percentage-cost.html",
      "systems/edrpg/templates/items/partials/item-ship-bonuses.html",
      "systems/edrpg/templates/items/partials/item-ship-life-support.html",
      "systems/edrpg/templates/items/partials/item-ship-range.html",
      "systems/edrpg/templates/items/partials/item-ship-strength.html",
      "systems/edrpg/templates/items/partials/item-ship-power-generated.html",
      "systems/edrpg/templates/items/partials/item-ship-power-consumed.html",
      "systems/edrpg/templates/items/partials/item-ship-effects.html",
      "systems/edrpg/templates/items/partials/item-ship-component-size.html",
      "systems/edrpg/templates/tests/skill-test.html",
      "systems/edrpg/templates/chat/message.html",
      "systems/edrpg/templates/chat/roll/skill.html",
    ]);
    game.settings.register("edrpg", "systemMaxBackgrounds", {
      name: "SETTINGS.systemMaxBackgroundsName",
      hint: "SETTINGS.systemMaxBackgroundsHint",
      scope: "world",
      config: true,
      default: 4,
      type: Number
    });
    game.settings.register("edrpg", "defaultDifficultyNumber", {
      name: "SETTINGS.defaultDifficultyNumberName",
      hint: "SETTINGS.defaultDifficultyNumberHint",
      scope: "world",
      config: true,
      default: 9,
      type: Number
    });
    game.settings.register("edrpg", "socialFactorCap", {
      name: "SETTINGS.socialFactorCapName",
      hint: "SETTINGS.socialFactorCapHint",
      scope: "world",
      config: true,
      default: 4,
      type: Number
    });
    game.settings.register("edrpg", "evolutionMaxSkillCap", {
      name: "SETTINGS.evolutionMaxSkillCapName",
      hint: "SETTINGS.evolutionMaxSkillCapHint",
      scope: "world",
      config: true,
      default: false,
      type: Boolean
    });
    game.settings.register("edrpg", "evolutionEnableEvolutionSkills", {
      name: "SETTINGS.evolutionEnableEvolutionSkillsName",
      hint: "SETTINGS.evolutionEnableEvolutionSkillsHint",
      scope: "world",
      config: true,
      default: false,
      type: Boolean
    });
    game.settings.register("edrpg", "allowToRerollAllTests", {
      name: "SETTINGS.allowToRerollAllTestsName",
      hint: "SETTINGS.allowToRerollAllTestsHint",
      scope: "world",
      config: true,
      default: false,
      type: Boolean
    });
  });
}
